### PR TITLE
Rebase branch and resolve merge conflicts

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by mlocati** [comment]
I think these are the changes needed to fix merge conflicts of https://github.com/punic/punic/pull/99

**Comment by c960657** [comment]
Is 289535c related to this PR? The other commits look fine.

**Comment by mlocati** [comment]
Whoops, you are right: I started from mlocati:master instead of punic:master...

**Comment by c960657** [comment]
👍

**Pull request merged**
